name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.10.0,19.6.1]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run:  npm run build
            mkdir staging && cp -r build staging
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
          name: my-artifact
          path: build
  pushToDockerHub:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - name: checkout repo
          uses: actions/checkout@v2
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: my-artifact
            path: build
        - name: Build and Push Docker Image
          uses: mr-smithers-excellent/docker-build-push@v5
          with:        
            image: glarimy/gap-ui
            tags: latest
            registry: docker.io
            dockerfile: dockerfile
            username: ${{SECRETS.DOCKER_ID}}
            password: ${{SECRETS.DOCKER_PWD}}     
